name: Actualizar cotizaciones BCRA

on:
  schedule:
    - cron: '0 21 * * *'  # Todos los dias 21:00 UTC
  workflow_dispatch:

jobs:
  run-bcra-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          ORIGIN_DB_URL: ${{ secrets.ORIGIN_DB_URL }}
        run: python main.py
