name: Scraper BCRA con Chrome Estable

on:
  push:
    branches:
      - main

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Google Chrome 138 y ChromeDriver 138
        run: |
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_138.0.7204.168-1_amd64.deb
          sudo dpkg -i google-chrome-stable_138.0.7204.168-1_amd64.deb || sudo apt-get -f install -y

          wget https://chromedriver.storage.googleapis.com/138.0.7204.168/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      - name: Ejecutar script
        run: python Ejercicio2/main.py
