name: BNRA_update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'  # corre los lunes a las 10:00 UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr xvfb
          wget https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Install Python dependencies
        run: |
          pip install selenium beautifulsoup4 python-dotenv pandas sqlalchemy psycopg2-binary

      - name: Run scraper with Xvfb (for headless Firefox)
        run: |
          xvfb-run -a python main.py
        env:
          ORIGIN_DB_URL: ${{ secrets.RENDER_DB_URL }}
