name: Test BCRA Requests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test_requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install requirements
        run: pip install -r requirements.txt
      
      - name: Run BCRA requests test
        run: python Ejercicio2/prueba_html.py
