name: Update Ventas

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2 AM UTC
  workflow_dispatch:  # Permite ejecución manual desde GitHub UI
  push:
    branches:
      - main

  
jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar main.py
      env:
        ORIGIN_DB_URL: ${{ secrets.ORIGIN_DB_URL }}
        DEST_DB_URL: ${{ secrets.RENDER_DB_URL }}
      run: python main.py